# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume_id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Resume ID')),
                ('name', models.CharField(max_length=100, verbose_name='Resume Name')),
            ],
            options={
                'verbose_name_plural': 'Resumes',
                'verbose_name': 'Resume',
            },
        ),
    ]
