# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_auto_20160502_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_name',
            new_name='name',
        ),
    ]
